const data=window.SITE_DATA;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const serviceGrid=$('#serviceGrid'),portfolioGrid=$('#portfolioGrid'),projectGrid=$('#projectGrid'),filters=$('#projectFilters');
serviceGrid.innerHTML=data.services.map(s=>`<article class="service-card"><div class="service-visual"><img src="${s.image}" alt="${s.title}"></div><div class="card-body"><div class="service-icon">${s.icon}</div><h3>${s.title}</h3><p>${s.short}</p><button class="text-link" data-type="service" data-id="${s.id}">Xem thêm →</button></div></article>`).join('');
portfolioGrid.innerHTML=data.portfolios.map(p=>`<article class="portfolio-card"><div class="portfolio-visual"><img src="${p.image}" alt="${p.title}"></div><div class="card-body"><h3>${p.title}</h3><p>${p.subtitle}</p><button class="text-link" data-type="portfolio" data-id="${p.id}">Xem chi tiết →</button></div></article>`).join('');
projectGrid.innerHTML=data.projects.map(p=>`<article class="project-card" data-category="${p.category}"><div class="project-visual"><img src="${p.image}" alt="${p.title}"></div><div class="card-body"><div class="project-meta"><span>${p.category}</span><span>${p.location}</span></div><h3>${p.title}</h3><button class="text-link" data-type="project" data-id="${p.id}">Xem chi tiết →</button></div></article>`).join('');
filters.innerHTML=data.categories.map((c,i)=>`<button class="filter-btn ${i===0?'active':''}" data-filter="${c}">${c}</button>`).join('');
filters.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;$$('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.project-card').forEach(card=>card.hidden=b.dataset.filter!=='Tất cả'&&card.dataset.category!==b.dataset.filter)});
const modal=$('#contentModal'),content=$('#modalContent');
function openModal(type,id){let item;if(type==='service'){item=data.services.find(x=>x.id===id);content.innerHTML=`<div class="modal-hero"><img src="${item.image}" alt="${item.title}"><div class="modal-title"><small>DỊCH VỤ</small><h2>${item.title.toUpperCase()}</h2></div></div><div class="modal-body"><div class="modal-body-grid"><div><h3>Giải pháp phù hợp từng công trình</h3><p>${item.short}</p><ul class="feature-list">${item.bullets.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="info-table"><h3>Quy trình đề xuất</h3><div class="info-row"><span>01</span><strong>Tiếp nhận nhu cầu</strong></div><div class="info-row"><span>02</span><strong>Khảo sát hiện trạng</strong></div><div class="info-row"><span>03</span><strong>Đề xuất giải pháp</strong></div><div class="info-row"><span>04</span><strong>Báo giá triển khai</strong></div><a class="btn btn-primary btn-full" href="#contact" data-close-modal>Liên hệ tư vấn</a></div></div></div>`}
if(type==='portfolio'){item=data.portfolios.find(x=>x.id===id);content.innerHTML=`<div class="modal-hero"><img src="${item.image}" alt="${item.title}"><div class="modal-title"><small>PORTFOLIO 2026</small><h2>${item.title.toUpperCase()}</h2></div></div><div class="modal-body"><h3>Nội dung hồ sơ</h3><p>Phiên bản website đang hiển thị dạng bộ trang. Có thể thay bằng PDF flipbook khi bạn cung cấp file PDF chính thức.</p><div class="page-list">${item.pages.map((x,i)=>`<div class="page-item"><small>TRANG ${String(i+1).padStart(2,'0')}</small><h3>${x}</h3></div>`).join('')}</div><button class="btn btn-primary">Mở file PDF (cập nhật sau)</button></div>`}
if(type==='project'){item=data.projects.find(x=>x.id===id);let idx=data.projects.indexOf(item),prev=data.projects[(idx-1+data.projects.length)%data.projects.length],next=data.projects[(idx+1)%data.projects.length];content.innerHTML=`<div class="modal-hero"><img src="${item.image}" alt="${item.title}"><div class="modal-title"><small>${item.location}</small><h2>${item.title.toUpperCase()}</h2></div></div><div class="modal-body"><div class="modal-body-grid"><div><h3>Tổng quan dự án</h3><p>${item.description}</p></div><div class="info-table">${Object.entries(item.info).map(([k,v])=>`<div class="info-row"><span>${k}</span><strong>${v}</strong></div>`).join('')}</div></div><div class="gallery">${item.gallery.map(x=>`<img src="${x}" alt="Hình ảnh ${item.title}">`).join('')}</div><div class="project-nav"><button data-switch-project="${prev.id}">← ${prev.title}</button><button data-switch-project="${next.id}">${next.title} →</button></div></div>`}
modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
document.addEventListener('click',e=>{const t=e.target.closest('[data-type]');if(t)openModal(t.dataset.type,t.dataset.id);if(e.target.closest('[data-close-modal]'))closeModal();const sw=e.target.closest('[data-switch-project]');if(sw)openModal('project',sw.dataset.switchProject)});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const toggle=$('.nav-toggle'),nav=$('.main-nav');toggle.addEventListener('click',()=>{nav.classList.toggle('open');toggle.setAttribute('aria-expanded',nav.classList.contains('open'))});$$('.main-nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
$('#contactForm').addEventListener('submit',e=>{e.preventDefault();$('#formNote').textContent='Đã ghi nhận nội dung demo. Hãy kết nối biểu mẫu thật trước khi xuất bản.';e.target.reset()});$('#year').textContent=new Date().getFullYear();
